// GENERATED by tools/generate-assets.mjs — do not edit by hand.
// Run `node tools/generate-assets.mjs` to regenerate.

export const palette = {
  "ink": "#20242a",
  "line": "#343a42",
  "softLine": "#6e7784",
  "paper": "#f4f1e9",
  "stone": "#b9b3a7",
  "stoneDark": "#777067",
  "steel": "#87909a",
  "steelDark": "#5d6670",
  "gold": "#d6a843",
  "ember": "#c9653b",
  "blood": "#9e3d43",
  "moss": "#5f8f73",
  "mint": "#8ec9a6",
  "teal": "#4d9aa0",
  "slate": "#2f4858",
  "blue": "#5f84b8",
  "violet": "#8a6fb0",
  "plum": "#5e496c",
  "bone": "#ded6c4",
  "shadow": "#00000024"
} as const;

export type SpriteId =
  | 'grimm-warrior'
  | 'vex-ranger'
  | 'mira-cleric'
  | 'slime'
  | 'skitter'
  | 'brute'
  | 'wraith'
  | 'lich'
  | 'floor'
  | 'wall'
  | 'stairs'
  | 'shrine'
  | 'sword'
  | 'bow'
  | 'staff'
  | 'potion'
  | 'gem'
  | 'skull'
  | 'scroll'
  | 'key'
  | 'coin';

export type SpriteEntry = {
  id: SpriteId;
  type: string;
  name: string;
  tags: readonly string[];
  url: string;
  svg: string;
};

export const sprites: Record<SpriteId, SpriteEntry> = {
  'grimm-warrior': {
    id: 'grimm-warrior',
    type: 'heroes',
    name: "Grimm",
    tags: ["hero","warrior","tank"] as const,
    url: '/assets/generated/heroes/grimm-warrior.svg',
    svg: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\" role=\"img\">\n  <rect width=\"64\" height=\"64\" fill=\"none\"/>\n  <g shape-rendering=\"geometricPrecision\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n\n    <ellipse cx=\"32\" cy=\"54\" rx=\"16\" ry=\"5\" fill=\"#00000024\" stroke=\"none\"/>\n    <path d=\"M19 30c0-10 5-18 13-18s13 8 13 18v10c0 8-5 13-13 13s-13-5-13-13z\" fill=\"#2f4858\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <path d=\"M21 30h24v9c0 6-5 10-12 10s-12-4-12-10z\" fill=\"#f4f1e9\" opacity=\".15\" stroke=\"none\"/>\n    <path d=\"M21 27c2-8 6-13 11-13s9 5 11 13H21z\" fill=\"#5d6670\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <circle cx=\"27\" cy=\"32\" r=\"1.8\" fill=\"#20242a\"/>\n    <circle cx=\"37\" cy=\"32\" r=\"1.8\" fill=\"#20242a\"/>\n    <path d=\"M28 37h8\" stroke=\"#343a42\" stroke-width=\"1.6\" fill=\"none\"/>\n    <path d=\"M49 18l3 3-18 18-3-3z\" fill=\"#87909a\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <path d=\"M47 24l-6-6\" stroke=\"#343a42\" stroke-width=\"2.2\"/>\n    <path d=\"M11 40l-4 3 3 4 4-3z\" fill=\"#87909a\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <path d=\"M30 21l2-4 2 4-2 3z\" fill=\"#d6a843\" stroke=\"#343a42\" stroke-width=\"1.2\"/>\n\n  </g>\n</svg>\n",
  },
  'vex-ranger': {
    id: 'vex-ranger',
    type: 'heroes',
    name: "Vex",
    tags: ["hero","ranger","dps"] as const,
    url: '/assets/generated/heroes/vex-ranger.svg',
    svg: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\" role=\"img\">\n  <rect width=\"64\" height=\"64\" fill=\"none\"/>\n  <g shape-rendering=\"geometricPrecision\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n\n    <ellipse cx=\"32\" cy=\"54\" rx=\"16\" ry=\"5\" fill=\"#00000024\" stroke=\"none\"/>\n    <path d=\"M19 30c0-10 5-18 13-18s13 8 13 18v10c0 8-5 13-13 13s-13-5-13-13z\" fill=\"#5f8f73\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <path d=\"M21 30h24v9c0 6-5 10-12 10s-12-4-12-10z\" fill=\"#f4f1e9\" opacity=\".15\" stroke=\"none\"/>\n    <path d=\"M21 27c2-8 6-13 11-13s9 5 11 13H21z\" fill=\"#5e496c\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <circle cx=\"27\" cy=\"32\" r=\"1.8\" fill=\"#20242a\"/>\n    <circle cx=\"37\" cy=\"32\" r=\"1.8\" fill=\"#20242a\"/>\n    <path d=\"M28 37h8\" stroke=\"#343a42\" stroke-width=\"1.6\" fill=\"none\"/>\n    <path d=\"M50 14c-4 6-4 22 0 34\" fill=\"none\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <path d=\"M50 14l0 34\" stroke=\"#ded6c4\" stroke-width=\"1\"/>\n    <path d=\"M50 30l6 0M44 30l-4 0\" stroke=\"#343a42\" stroke-width=\"1.6\" fill=\"none\"/>\n    <path d=\"M28 20h8l-4 5z\" fill=\"#8ec9a6\" stroke=\"#343a42\" stroke-width=\"1.2\"/>\n\n  </g>\n</svg>\n",
  },
  'mira-cleric': {
    id: 'mira-cleric',
    type: 'heroes',
    name: "Mira",
    tags: ["hero","cleric","support"] as const,
    url: '/assets/generated/heroes/mira-cleric.svg',
    svg: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\" role=\"img\">\n  <rect width=\"64\" height=\"64\" fill=\"none\"/>\n  <g shape-rendering=\"geometricPrecision\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n\n    <ellipse cx=\"32\" cy=\"54\" rx=\"16\" ry=\"5\" fill=\"#00000024\" stroke=\"none\"/>\n    <path d=\"M19 30c0-10 5-18 13-18s13 8 13 18v10c0 8-5 13-13 13s-13-5-13-13z\" fill=\"#8a6fb0\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <path d=\"M21 30h24v9c0 6-5 10-12 10s-12-4-12-10z\" fill=\"#f4f1e9\" opacity=\".15\" stroke=\"none\"/>\n    <path d=\"M21 27c2-8 6-13 11-13s9 5 11 13H21z\" fill=\"#5e496c\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <circle cx=\"27\" cy=\"32\" r=\"1.8\" fill=\"#20242a\"/>\n    <circle cx=\"37\" cy=\"32\" r=\"1.8\" fill=\"#20242a\"/>\n    <path d=\"M28 37h8\" stroke=\"#343a42\" stroke-width=\"1.6\" fill=\"none\"/>\n    <path d=\"M49 15v28\" stroke=\"#5d6670\" stroke-width=\"2.6\" stroke-linecap=\"round\"/>\n    <circle cx=\"49\" cy=\"13\" r=\"4\" fill=\"#d6a843\" stroke=\"#343a42\" stroke-width=\"1.6\"/>\n    <path d=\"M46 13h6M49 10v6\" stroke=\"#20242a\" stroke-width=\"1.2\"/>\n    <path d=\"M29 20h6v6h-6z\" fill=\"#ded6c4\" stroke=\"#343a42\" stroke-width=\"1.2\"/>\n\n  </g>\n</svg>\n",
  },
  'slime': {
    id: 'slime',
    type: 'enemies',
    name: "Slime",
    tags: ["enemy","blob"] as const,
    url: '/assets/generated/enemies/slime.svg',
    svg: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\" role=\"img\">\n  <rect width=\"64\" height=\"64\" fill=\"none\"/>\n  <g shape-rendering=\"geometricPrecision\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n\n    <ellipse cx=\"32\" cy=\"54\" rx=\"16\" ry=\"5\" fill=\"#00000024\" stroke=\"none\"/>\n    <path d=\"M12 44c0-12 8-20 20-20s20 8 20 20c0 4-2 6-6 6H18c-4 0-6-2-6-6z\" fill=\"#5f8f73\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n\n    <circle cx=\"26\" cy=\"38\" r=\"2\" fill=\"#f4f1e9\"/>\n    <circle cx=\"38\" cy=\"38\" r=\"2\" fill=\"#f4f1e9\"/>\n    <circle cx=\"26\" cy=\"38.3\" r=\"0.8\" fill=\"#20242a\"/>\n    <circle cx=\"38\" cy=\"38.3\" r=\"0.8\" fill=\"#20242a\"/>\n    <path d=\"M27 44c3 2 7 2 10 0\" stroke=\"#343a42\" stroke-width=\"1.6\" fill=\"none\"/>\n\n  </g>\n</svg>\n",
  },
  'skitter': {
    id: 'skitter',
    type: 'enemies',
    name: "Skitter",
    tags: ["enemy","bug"] as const,
    url: '/assets/generated/enemies/skitter.svg',
    svg: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\" role=\"img\">\n  <rect width=\"64\" height=\"64\" fill=\"none\"/>\n  <g shape-rendering=\"geometricPrecision\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n\n    <ellipse cx=\"32\" cy=\"54\" rx=\"16\" ry=\"5\" fill=\"#00000024\" stroke=\"none\"/>\n    <path d=\"M14 38c4-12 10-18 18-18s14 6 18 18c-5 8-11 12-18 12s-13-4-18-12z\" fill=\"#c9653b\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <path d=\"M18 32L8 26M46 32l10-6M20 44l-10 5M44 44l10 5\" stroke=\"#343a42\" stroke-width=\"1.6\" fill=\"none\"/>\n    <circle cx=\"27\" cy=\"34\" r=\"2\" fill=\"#f4f1e9\"/>\n    <circle cx=\"37\" cy=\"34\" r=\"2\" fill=\"#f4f1e9\"/>\n    <circle cx=\"27\" cy=\"34.3\" r=\"0.8\" fill=\"#20242a\"/>\n    <circle cx=\"37\" cy=\"34.3\" r=\"0.8\" fill=\"#20242a\"/>\n    <path d=\"M26 40c4 3 8 3 12 0\" stroke=\"#343a42\" stroke-width=\"1.6\" fill=\"none\"/>\n\n  </g>\n</svg>\n",
  },
  'brute': {
    id: 'brute',
    type: 'enemies',
    name: "Brute",
    tags: ["enemy","frontline"] as const,
    url: '/assets/generated/enemies/brute.svg',
    svg: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\" role=\"img\">\n  <rect width=\"64\" height=\"64\" fill=\"none\"/>\n  <g shape-rendering=\"geometricPrecision\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n\n    <ellipse cx=\"32\" cy=\"54\" rx=\"16\" ry=\"5\" fill=\"#00000024\" stroke=\"none\"/>\n    <path d=\"M16 34c0-12 7-21 16-21s16 9 16 21c0 11-7 18-16 18s-16-7-16-18z\" fill=\"#9e3d43\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <path d=\"M22 17l-3-6M42 17l3-6\" stroke=\"#343a42\" stroke-width=\"1.6\" fill=\"none\"/>\n    <circle cx=\"27\" cy=\"30\" r=\"2\" fill=\"#f4f1e9\"/>\n    <circle cx=\"37\" cy=\"30\" r=\"2\" fill=\"#f4f1e9\"/>\n    <circle cx=\"27\" cy=\"30.3\" r=\"0.8\" fill=\"#20242a\"/>\n    <circle cx=\"37\" cy=\"30.3\" r=\"0.8\" fill=\"#20242a\"/>\n    <path d=\"M26 40c4 3 8 3 12 0\" stroke=\"#343a42\" stroke-width=\"1.6\" fill=\"none\"/>\n\n  </g>\n</svg>\n",
  },
  'wraith': {
    id: 'wraith',
    type: 'enemies',
    name: "Wraith",
    tags: ["enemy","caster"] as const,
    url: '/assets/generated/enemies/wraith.svg',
    svg: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\" role=\"img\">\n  <rect width=\"64\" height=\"64\" fill=\"none\"/>\n  <g shape-rendering=\"geometricPrecision\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n\n    <ellipse cx=\"32\" cy=\"54\" rx=\"16\" ry=\"5\" fill=\"#00000024\" stroke=\"none\"/>\n    <path d=\"M18 16c4-4 9-6 14-6s10 2 14 6l-2 30-4-4-3 6-3-6-2 6-3-6-3 6-4-6-2 4z\" fill=\"#5e496c\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n\n    <circle cx=\"27\" cy=\"24\" r=\"2\" fill=\"#f4f1e9\"/>\n    <circle cx=\"37\" cy=\"24\" r=\"2\" fill=\"#f4f1e9\"/>\n    <circle cx=\"27\" cy=\"24.3\" r=\"0.8\" fill=\"#20242a\"/>\n    <circle cx=\"37\" cy=\"24.3\" r=\"0.8\" fill=\"#20242a\"/>\n    <path d=\"M28 32c3 2 5 2 8 0\" stroke=\"#343a42\" stroke-width=\"1.6\" fill=\"none\"/>\n\n  </g>\n</svg>\n",
  },
  'lich': {
    id: 'lich',
    type: 'enemies',
    name: "Lich",
    tags: ["enemy","undead"] as const,
    url: '/assets/generated/enemies/lich.svg',
    svg: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\" role=\"img\">\n  <rect width=\"64\" height=\"64\" fill=\"none\"/>\n  <g shape-rendering=\"geometricPrecision\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n\n    <ellipse cx=\"32\" cy=\"54\" rx=\"16\" ry=\"5\" fill=\"#00000024\" stroke=\"none\"/>\n    <path d=\"M14 22c0-8 8-14 18-14s18 6 18 14l-3 24c-4 4-9 6-15 6s-11-2-15-6z\" fill=\"#777067\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <path d=\"M22 12l-3-6M42 12l3-6M32 6v-4\" stroke=\"#343a42\" stroke-width=\"1.6\" fill=\"none\"/>\n    <circle cx=\"27\" cy=\"24\" r=\"2\" fill=\"#f4f1e9\"/>\n    <circle cx=\"37\" cy=\"24\" r=\"2\" fill=\"#f4f1e9\"/>\n    <circle cx=\"27\" cy=\"24.3\" r=\"0.8\" fill=\"#20242a\"/>\n    <circle cx=\"37\" cy=\"24.3\" r=\"0.8\" fill=\"#20242a\"/>\n    <path d=\"M26 36l3 3 3-3 3 3 3-3\" stroke=\"#343a42\" stroke-width=\"1.6\" fill=\"none\"/>\n\n  </g>\n</svg>\n",
  },
  'floor': {
    id: 'floor',
    type: 'tiles',
    name: "Floor",
    tags: ["tile"] as const,
    url: '/assets/generated/tiles/floor.svg',
    svg: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\" role=\"img\">\n  <rect width=\"64\" height=\"64\" fill=\"none\"/>\n  <g shape-rendering=\"geometricPrecision\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n\n    <rect x=\"6\" y=\"6\" width=\"52\" height=\"52\" rx=\"6\" fill=\"#b9b3a7\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <path d=\"M7 24h50M24 7v50M42 7v50M7 42h50\" stroke=\"#777067\" stroke-width=\"1.2\" fill=\"none\" opacity=\".5\"/>\n\n  </g>\n</svg>\n",
  },
  'wall': {
    id: 'wall',
    type: 'tiles',
    name: "Wall",
    tags: ["tile"] as const,
    url: '/assets/generated/tiles/wall.svg',
    svg: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\" role=\"img\">\n  <rect width=\"64\" height=\"64\" fill=\"none\"/>\n  <g shape-rendering=\"geometricPrecision\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n\n    <rect x=\"6\" y=\"6\" width=\"52\" height=\"52\" rx=\"6\" fill=\"#777067\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <path d=\"M8 19h48M8 35h48M8 51h48M22 7v12M42 19v16M26 35v16\" stroke=\"#b9b3a7\" stroke-width=\"1.5\" fill=\"none\" opacity=\".7\"/>\n\n  </g>\n</svg>\n",
  },
  'stairs': {
    id: 'stairs',
    type: 'tiles',
    name: "Stairs",
    tags: ["tile","descent"] as const,
    url: '/assets/generated/tiles/stairs.svg',
    svg: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\" role=\"img\">\n  <rect width=\"64\" height=\"64\" fill=\"none\"/>\n  <g shape-rendering=\"geometricPrecision\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n\n    <rect x=\"6\" y=\"6\" width=\"52\" height=\"52\" rx=\"6\" fill=\"#5e496c\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <path d=\"M14 46h36v6H14z\" fill=\"#20242a\" stroke=\"#343a42\" stroke-width=\"1.6\"/>\n    <path d=\"M20 40h30v6H20z\" fill=\"#777067\" stroke=\"#343a42\" stroke-width=\"1.6\"/>\n    <path d=\"M26 34h24v6H26z\" fill=\"#b9b3a7\" stroke=\"#343a42\" stroke-width=\"1.6\"/>\n    <path d=\"M32 28h18v6H32z\" fill=\"#ded6c4\" stroke=\"#343a42\" stroke-width=\"1.6\"/>\n    <path d=\"M38 22h12v6H38z\" fill=\"#f4f1e9\" stroke=\"#343a42\" stroke-width=\"1.6\"/>\n\n  </g>\n</svg>\n",
  },
  'shrine': {
    id: 'shrine',
    type: 'tiles',
    name: "Shrine",
    tags: ["tile","rest"] as const,
    url: '/assets/generated/tiles/shrine.svg',
    svg: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\" role=\"img\">\n  <rect width=\"64\" height=\"64\" fill=\"none\"/>\n  <g shape-rendering=\"geometricPrecision\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n\n    <rect x=\"6\" y=\"6\" width=\"52\" height=\"52\" rx=\"6\" fill=\"#b9b3a7\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <path d=\"M20 47h24M24 47V28l8-12 8 12v19\" fill=\"#ded6c4\" stroke=\"#343a42\" stroke-width=\"1.6\"/>\n    <path d=\"M32 25v14M25 32h14\" stroke=\"#343a42\" stroke-width=\"1.6\" fill=\"none\"/>\n\n  </g>\n</svg>\n",
  },
  'sword': {
    id: 'sword',
    type: 'items',
    name: "Sword",
    tags: ["weapon"] as const,
    url: '/assets/generated/items/sword.svg',
    svg: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\" role=\"img\">\n  <rect width=\"64\" height=\"64\" fill=\"none\"/>\n  <g shape-rendering=\"geometricPrecision\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n\n    <ellipse cx=\"32\" cy=\"54\" rx=\"16\" ry=\"5\" fill=\"#00000024\" stroke=\"none\"/>\n    <path d=\"M32 8l4 32-4 8-4-8z\" fill=\"#87909a\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <path d=\"M22 38h20\" stroke=\"#d6a843\" stroke-width=\"3\" stroke-linecap=\"round\"/>\n    <path d=\"M30 44h4v8h-4z\" fill=\"#5e496c\" stroke=\"#343a42\" stroke-width=\"1.6\"/>\n\n  </g>\n</svg>\n",
  },
  'bow': {
    id: 'bow',
    type: 'items',
    name: "Bow",
    tags: ["weapon"] as const,
    url: '/assets/generated/items/bow.svg',
    svg: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\" role=\"img\">\n  <rect width=\"64\" height=\"64\" fill=\"none\"/>\n  <g shape-rendering=\"geometricPrecision\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n\n    <ellipse cx=\"32\" cy=\"54\" rx=\"16\" ry=\"5\" fill=\"#00000024\" stroke=\"none\"/>\n    <path d=\"M18 12C34 20 34 44 18 52\" fill=\"none\" stroke=\"#343a42\" stroke-width=\"2.6\" stroke-linecap=\"round\"/>\n    <path d=\"M18 12L18 52\" stroke=\"#ded6c4\" stroke-width=\"1\"/>\n    <path d=\"M34 32l12 0\" stroke=\"#343a42\" stroke-width=\"2\" stroke-linecap=\"round\"/>\n    <path d=\"M42 28l6 4-6 4\" fill=\"#c9653b\" stroke=\"#343a42\" stroke-width=\"1.6\"/>\n\n  </g>\n</svg>\n",
  },
  'staff': {
    id: 'staff',
    type: 'items',
    name: "Staff",
    tags: ["weapon"] as const,
    url: '/assets/generated/items/staff.svg',
    svg: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\" role=\"img\">\n  <rect width=\"64\" height=\"64\" fill=\"none\"/>\n  <g shape-rendering=\"geometricPrecision\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n\n    <ellipse cx=\"32\" cy=\"54\" rx=\"16\" ry=\"5\" fill=\"#00000024\" stroke=\"none\"/>\n    <path d=\"M32 16v36\" stroke=\"#5d6670\" stroke-width=\"3\" stroke-linecap=\"round\"/>\n    <circle cx=\"32\" cy=\"14\" r=\"6\" fill=\"#d6a843\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <path d=\"M28 14h8M32 10v8\" stroke=\"#20242a\" stroke-width=\"1.4\"/>\n\n  </g>\n</svg>\n",
  },
  'potion': {
    id: 'potion',
    type: 'items',
    name: "Potion",
    tags: ["consumable"] as const,
    url: '/assets/generated/items/potion.svg',
    svg: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\" role=\"img\">\n  <rect width=\"64\" height=\"64\" fill=\"none\"/>\n  <g shape-rendering=\"geometricPrecision\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n\n    <ellipse cx=\"32\" cy=\"54\" rx=\"16\" ry=\"5\" fill=\"#00000024\" stroke=\"none\"/>\n    <path d=\"M26 12h12v8M26 20c-4 4-6 10-6 16s4 12 12 12 12-6 12-12-2-12-6-16\" fill=\"#8ec9a6\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <path d=\"M22 14h20\" stroke=\"#343a42\" stroke-width=\"2.4\" stroke-linecap=\"round\"/>\n    <ellipse cx=\"32\" cy=\"38\" rx=\"6\" ry=\"4\" fill=\"#f4f1e9\" opacity=\".4\"/>\n\n  </g>\n</svg>\n",
  },
  'gem': {
    id: 'gem',
    type: 'items',
    name: "Gem",
    tags: ["loot"] as const,
    url: '/assets/generated/items/gem.svg',
    svg: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\" role=\"img\">\n  <rect width=\"64\" height=\"64\" fill=\"none\"/>\n  <g shape-rendering=\"geometricPrecision\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n\n    <ellipse cx=\"32\" cy=\"54\" rx=\"16\" ry=\"5\" fill=\"#00000024\" stroke=\"none\"/>\n    <path d=\"M20 26l12-14 12 14L32 52z\" fill=\"#4d9aa0\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <path d=\"M20 26h24M26 26l6-14M38 26l-6-14M26 26l6 12M38 26l-6 12\" stroke=\"#343a42\" stroke-width=\"1.2\" fill=\"none\" opacity=\".7\"/>\n\n  </g>\n</svg>\n",
  },
  'skull': {
    id: 'skull',
    type: 'items',
    name: "Skull",
    tags: ["macabre"] as const,
    url: '/assets/generated/items/skull.svg',
    svg: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\" role=\"img\">\n  <rect width=\"64\" height=\"64\" fill=\"none\"/>\n  <g shape-rendering=\"geometricPrecision\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n\n    <ellipse cx=\"32\" cy=\"54\" rx=\"16\" ry=\"5\" fill=\"#00000024\" stroke=\"none\"/>\n    <path d=\"M16 26c0-10 7-16 16-16s16 6 16 16v10c0 4-3 6-6 6l-2 6h-16l-2-6c-3 0-6-2-6-6z\" fill=\"#ded6c4\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <circle cx=\"25\" cy=\"30\" r=\"3\" fill=\"#20242a\"/>\n    <circle cx=\"39\" cy=\"30\" r=\"3\" fill=\"#20242a\"/>\n    <path d=\"M29 40l3-3 3 3\" stroke=\"#343a42\" stroke-width=\"1.6\" fill=\"none\"/>\n    <path d=\"M26 48h12\" stroke=\"#343a42\" stroke-width=\"1.4\"/>\n\n  </g>\n</svg>\n",
  },
  'scroll': {
    id: 'scroll',
    type: 'items',
    name: "Scroll",
    tags: ["lore"] as const,
    url: '/assets/generated/items/scroll.svg',
    svg: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\" role=\"img\">\n  <rect width=\"64\" height=\"64\" fill=\"none\"/>\n  <g shape-rendering=\"geometricPrecision\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n\n    <ellipse cx=\"32\" cy=\"54\" rx=\"16\" ry=\"5\" fill=\"#00000024\" stroke=\"none\"/>\n    <rect x=\"12\" y=\"18\" width=\"40\" height=\"28\" rx=\"2\" fill=\"#f4f1e9\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <path d=\"M10 18c4 0 4 4 4 14s0 14-4 14c6-2 6-10 6-14s0-12-6-14z\" fill=\"#ded6c4\" stroke=\"#343a42\" stroke-width=\"1.6\"/>\n    <path d=\"M54 18c-4 0-4 4-4 14s0 14 4 14c-6-2-6-10-6-14s0-12 6-14z\" fill=\"#ded6c4\" stroke=\"#343a42\" stroke-width=\"1.6\"/>\n    <path d=\"M18 26h28M18 32h22M18 38h26\" stroke=\"#6e7784\" stroke-width=\"1.2\" fill=\"none\"/>\n\n  </g>\n</svg>\n",
  },
  'key': {
    id: 'key',
    type: 'items',
    name: "Key",
    tags: ["unlock"] as const,
    url: '/assets/generated/items/key.svg',
    svg: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\" role=\"img\">\n  <rect width=\"64\" height=\"64\" fill=\"none\"/>\n  <g shape-rendering=\"geometricPrecision\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n\n    <ellipse cx=\"32\" cy=\"54\" rx=\"16\" ry=\"5\" fill=\"#00000024\" stroke=\"none\"/>\n    <circle cx=\"22\" cy=\"32\" r=\"10\" fill=\"none\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <circle cx=\"22\" cy=\"32\" r=\"3\" fill=\"#20242a\"/>\n    <path d=\"M32 32h22M48 32v6M52 32v4\" stroke=\"#343a42\" stroke-width=\"2.4\" stroke-linecap=\"round\" fill=\"none\"/>\n\n  </g>\n</svg>\n",
  },
  'coin': {
    id: 'coin',
    type: 'items',
    name: "Coin",
    tags: ["loot"] as const,
    url: '/assets/generated/items/coin.svg',
    svg: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\" role=\"img\">\n  <rect width=\"64\" height=\"64\" fill=\"none\"/>\n  <g shape-rendering=\"geometricPrecision\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n\n    <ellipse cx=\"32\" cy=\"54\" rx=\"16\" ry=\"5\" fill=\"#00000024\" stroke=\"none\"/>\n    <circle cx=\"32\" cy=\"32\" r=\"16\" fill=\"#d6a843\" stroke=\"#343a42\" stroke-width=\"2.4\"/>\n    <circle cx=\"32\" cy=\"32\" r=\"11\" fill=\"none\" stroke=\"#343a42\" stroke-width=\"1\"/>\n    <path d=\"M28 24l4 16 4-16\" stroke=\"#343a42\" stroke-width=\"2\" fill=\"none\" stroke-linecap=\"round\"/>\n\n  </g>\n</svg>\n",
  },
};

export function spriteById(id: SpriteId): SpriteEntry {
  return sprites[id];
}
